---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
  # Uncomment additional architectures if supported
  # armv7: "ghcr.io/home-assistant/armv7-base:3.23"
  # armhf: "ghcr.io/home-assistant/armhf-base:3.23"
  # i386: "ghcr.io/home-assistant/i386-base:3.23"
labels:
  maintainer: "Your Name <email@example.com>"
  org.opencontainers.image.authors: "Your Name <email@example.com>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Add-on: Your Add-on"
  org.opencontainers.image.description: "A brief description of your add-on"
  org.opencontainers.image.url: https://github.com/{username}/{repository}
  org.opencontainers.image.source: https://github.com/{username}/{repository}/tree/main/{addon_directory}
  org.opencontainers.image.documentation: https://github.com/{username}/{repository}/blob/main/{addon_directory}/README.md
  org.opencontainers.image.created: "2025-01-27T00:00:00Z"
  org.opencontainers.image.revision: "git-commit-sha"
  org.opencontainers.image.version: "1.0.0"
args:
  # Add custom build arguments here
  # EXAMPLE_VERSION: "1.0.0"
