---
# Domain Path Configuration
# Single source of truth for path ownership and routing

domains:
  huntarr:
    paths:
      - huntarr/**
    base_branch: main

  profilarr:
    paths:
      - profilarr/**
    base_branch: main

  romm:
    paths:
      - romm/**
    base_branch: main

  docs:
    paths:
      - docs/**
    base_branch: main

  workflows:
    paths:
      - .github/workflows/**
    base_branch: main
