---
# Domain Path Configuration
# Single source of truth for path ownership and routing

domains:
  huntarr:
    paths:
      - huntarr/**
    base_branch: main

  profilarr:
    paths:
      - profilarr/**
    base_branch: main

  romm:
    paths:
      - romm/**
    base_branch: main

  cleanuparr:
    paths:
      - cleanuparr/**
    base_branch: main
