---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
labels:
  project: "https://github.com/Cleanuparr/Cleanuparr"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: cleanuparr"
  org.opencontainers.image.description: "Automated cleanup for Sonarr, Radarr, and download clients"
  org.opencontainers.image.source: "https://github.com/rigerc/home-assistant-addons/cleanuparr"
  io.hass.upstream.image: "ghcr.io/cleanuparr/cleanuparr"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/cleanuparr/README.md
  org.opencontainers.image.created: "2026-02-03T00:09:47Z"
  org.opencontainers.image.revision: 70e2cdd22325c033bad29dde3e467c783fd8e1c2
  org.opencontainers.image.version: "0.2.14"
