---
# Build Configuration for Cleanuparr Add-on
# This file configures the build process for the Home Assistant add-on

# Base Images per Architecture
# Using Home Assistant's minimal base images (Alpine Linux 3.20)
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"

# Build Arguments
# These are passed to the Dockerfile during build
args:
  CLEANUPARR_VERSION: "2.5.1"
  BUILD_DATE: "2024-01-27"

# Docker Labels
# Metadata for the container image
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Cleanuparr"
  org.opencontainers.image.description: "Automated cleanup for Sonarr, Radarr, Lidarr, Readarr, and Whisparr downloads"
  org.opencontainers.image.source: "https://github.com/your-username/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
  org.opencontainers.image.authors: "Your Name <you@example.com>"
  org.opencontainers.image.created: "${BUILD_DATE}"
  org.opencontainers.image.version: "${CLEANUPARR_VERSION}"

# Codenotary Configuration
# Optional: Sign your images for verification (+1 security point)
# codenotary:
#   signer: "developer@example.com"
#   base_image: "notary@home-assistant.io"
