---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"

# Docker Labels
# Metadata for the container image
labels:
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: cleanuparr"
  org.opencontainers.image.description: "Automated cleanup for Sonarr, Radarr, Lidarr, Readarr, and Whisparr downloads"
  org.opencontainers.image.source: "https://github.com/rigerc/home-assistant-addons/cleanuparr"
  org.opencontainers.image.licenses: "Apache License 2.0"
  org.opencontainers.image.authors: "Your Name <you@example.com>"
  org.opencontainers.image.created: "${BUILD_DATE}"
  org.opencontainers.image.version: "${BUILD_VERSION}"

# Codenotary Configuration
# Optional: Sign your images for verification (+1 security point)
# codenotary:
#   signer: "developer@example.com"
#   base_image: "notary@home-assistant.io"
