---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Cleanuparr"
  org.opencontainers.image.description: "Automated cleanup for Sonarr, Radarr, and download clients"
  org.opencontainers.image.source: "https://github.com/Cleanuparr/Cleanuparr"
  io.hass.upstream.image: "ghcr.io/cleanuparr/cleanuparr"
