# Example GitHub Actions workflow for release-please
# Place this in .github/workflows/release-please.yml

on:
  push:
    branches:
      - main
  # Allow manual workflow trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # Create release PR
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main

  # Optional: Build/publish after release
  publish:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Example: Node.js publish
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
