---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  project: "https://github.com/rommapp/romm"
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "rigerc"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: romm"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.source: https://github.com/rigerc/home-assistant-addons/romm
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/romm/README.md
  org.opencontainers.image.created: "2026-02-03T01:58:05Z"
  org.opencontainers.image.revision: 6f92298c99f2cecf7b2e4bd03553d11652c98e94
  org.opencontainers.image.version: 0.1.27
