---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
labels:
  project: "https://github.com/Dictionarry-Hub/profilarr"
  maintainer: "rigerc"
  org.opencontainers.image.authors: "rigerc"
  org.opencontainers.image.licenses: "AGPL-3.0"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: Profilarr V2"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.source: https://github.com/rigerc/home-assistant-addons/profilarr-v2
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/profilarr-v2/README.md
