---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
project: "https://github.com/Dictionarry-Hub/profilarr"
labels:
  maintainer: "rigerc"
  org.opencontainers.image.authors: "rigerc"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: Profilarr"
  org.opencontainers.image.description: "Profile manager for Radarr and Sonarr instances"
  org.opencontainers.image.source: "https://github.com/rigerc/home-assistant-addons/profilarr"
  io.hass.upstream.image: "santiagosayshey/profilarr"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/profilarr/README.md
