---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
labels:
  project: "https://github.com/Dictionarry-Hub/profilarr"
  maintainer: "rigerc"
  org.opencontainers.image.authors: "rigerc"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: profilarr"
  org.opencontainers.image.description: "Profile manager for Radarr and Sonarr instances"
  org.opencontainers.image.source: "https://github.com/rigerc/home-assistant-addons/profilarr"
  io.hass.upstream.image: "santiagosayshey/profilarr"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/profilarr/README.md
  org.opencontainers.image.created: "2026-02-02T00:24:07Z"
  org.opencontainers.image.revision: bf1cf97ddb77b1c1dfac0f31838e3284ef28507f
  org.opencontainers.image.version: 1.0.5
