---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
labels:
  project: "https://github.com/plexguide/Huntarr.io"
  maintainer: "rigerc"
  org.opencontainers.image.authors: "rigerc"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: huntarr"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.source: https://github.com/rigerc/home-assistant-addons/huntarr
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/huntarr/README.md
  org.opencontainers.image.created: "2026-02-01T20:52:58Z"
  org.opencontainers.image.revision: 248c42851bfa91a7b19555ad9ec30f7be2e0f3d6
  org.opencontainers.image.version: 0.1.3
