---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
project: "https://github.com/plexguide/Huntarr.io"
labels:
  maintainer: "rigerc"
  org.opencontainers.image.authors: "rigerc"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: huntarr"
  org.opencontainers.image.url: https://github.com/rigerc/home-assistant-addons
  org.opencontainers.image.source: https://github.com/rigerc/home-assistant-addons/huntarr
  org.opencontainers.image.documentation: https://github.com/rigerc/home-assistant-addons/huntarr/README.md
  org.opencontainers.image.created: "2026-01-31T22:12:34Z"
  org.opencontainers.image.revision: cbb63dfa1797a4caf9f83d092fc7db4fcfe3a3b5
  org.opencontainers.image.version: 0.1.1
