# Reusable workflow that can be called from other workflows
name: Reusable Test
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '20'
        type: string
    outputs:
      coverage:
        value: ${{ jobs.test.outputs.coverage }}
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.cov.outputs.pct }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - run: npm ci
      - run: npm test
      - id: cov
        run: echo "pct=95" >> $GITHUB_OUTPUT
# Usage: jobs: test: uses: ./.github/workflows/reusable-workflow.yml
