# Scheduled maintenance tasks
name: Scheduled Cleanup
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Stale - will close in 7 days'
          days-before-stale: 90
          days-before-close: 7
