# Scheduled Workflow
# Run scheduled tasks for maintenance and reporting

name: Scheduled Tasks

on:
  schedule:
    # Daily at 00:00 UTC
    - cron: '0 0 * * *'
    # Weekly on Monday at 06:00 UTC
    - cron: '0 6 * * 1'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      task:
        description: 'Task to run'
        required: true
        type: choice
        options:
          - dependency-check
          - cleanup
          - report

jobs:
  # Check for dependency updates
  dependency-check:
    name: Dependency Check
    if: |
      github.event.schedule == '0 6 * * 1' ||
      (github.event_name == 'workflow_dispatch' && inputs.task == 'dependency-check')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check for outdated dependencies
        run: |
          npm outdated --json > outdated.json || true

      - name: Create issue if updates available
        if: hashFiles('outdated.json') != hashFiles('')
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const outdated = JSON.parse(fs.readFileSync('outdated.json', 'utf8'));
            if (Object.keys(outdated).length > 0) {
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Dependency Updates Available',
                body: 'The following dependencies have updates available:\n\n' +
                      Object.entries(outdated).map(([name, info]) =>
                        `- **${name}**: ${info.current} → ${info.latest}`
                      ).join('\n'),
                labels: ['dependencies', 'maintenance']
              });
            }

  # Cleanup old artifacts
  cleanup:
    name: Cleanup Artifacts
    if: |
      github.event.schedule == '0 0 * * *' ||
      (github.event_name == 'workflow_dispatch' && inputs.task == 'cleanup')
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - 30);
            for (const artifact of artifacts.data.artifacts) {
              const createdDate = new Date(artifact.created_at);
              if (createdDate < cutoffDate) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
                console.log(`Deleted artifact: ${artifact.name}`);
              }
            }

  # Generate weekly report
  report:
    name: Weekly Report
    if: |
      github.event.schedule == '0 6 * * 1' ||
      (github.event_name == 'workflow_dispatch' && inputs.task == 'report')
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - name: Generate report
        id: report
        uses: actions/github-script@v7
        with:
          script: |
            // Get issues from last week
            const oneWeekAgo = new Date();
            oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              since: oneWeekAgo.toISOString(),
              state: 'all'
            });
            const openIssues = issues.data.filter(i => i.state === 'open').length;
            const closedIssues = issues.data.filter(i => i.state === 'closed').length;
            // Get PRs from last week
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              created: `>=${oneWeekAgo.toISOString()}`
            });
            const openPRs = pulls.data.length;
            // Create summary
            const summary = `# Weekly Report\n\n` +
              `- **Open Issues**: ${openIssues}\n` +
              `- **Closed Issues**: ${closedIssues}\n` +
              `- **Open Pull Requests**: ${openPRs}\n`;
            await core.summary
              .addRaw(summary)
              .write();
            core.setOutput('summary', summary);
