#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
# ==============================================================================
# Configure application environment
# s6-overlay v3: Runs during stage 2, before services start
# ==============================================================================

set -e

bashio::log.info "Configuring application..."

#####################
# CREATE DIRECTORIES #
#####################

mkdir -p /data/config
mkdir -p /data/logs

bashio::log.info "Created required directories"

#######################
# LOAD CONFIGURATION #
#######################

LOG_LEVEL=$(bashio::config 'log_level')

bashio::log.info "Log level set to: ${LOG_LEVEL}"

#######################
# GENERATE CONFIG #
#######################

# Generate application configuration file
cat > /data/config/app.conf <<EOF
# Generated by Home Assistant Add-on
log_level=${LOG_LEVEL}
data_path=/data
config_path=/data/config
log_path=/data/logs
EOF

bashio::log.info "Application configuration generated"

#######################
# VALIDATE CONFIG #
#######################

# Example: Validate required settings
# if ! bashio::config.has_value 'required_field'; then
#     bashio::exit.nok "Required configuration 'required_field' is missing"
# fi

bashio::log.info "Application setup complete"
