---
name: README Updates
description: "Update all or given READMEs using manifest.json"

inputs:
  addons:
    description: Addon-Name(s)
    required: false

runs:
  using: "composite"
  steps:
    - name: Install jq
      uses: dcarbone/install-jq-action@v3

    - name: Setup gomplate
      shell: bash
      run: |
        GOMPLATE_VERSION="${GOMPLATE_VERSION:-v4.3.0}"
        curl -o /usr/local/bin/gomplate -sSL "https://github.com/hairyhenderson/gomplate/releases/download/${GOMPLATE_VERSION}/gomplate_linux-amd64"
        chmod +x /usr/local/bin/gomplate
        gomplate --version

    - name: ℹ️ Gather Addon Info
      id: info
      shell: bash
      run: |
        set -euo pipefail

        if [[ ! -f "manifest.json" ]]; then
          echo "Error: manifest.json not found"
          exit 1
        fi

        # Read all addons from manifest.json
        addons_json=$(jq -c '.' manifest.json)
        addon_slugs=$(jq -r '.[].slug' manifest.json)

        echo "addons=${addons_json}" >> $GITHUB_OUTPUT
        echo "readme=${addon_slugs}" >> $GITHUB_OUTPUT
        echo "Addons: ${addon_slugs}"

    - name: 📝 Generate README.md
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        REPOSITORY_URL: https://github.com/${{ github.repository }}
        AUTHOR_NAME: ${{ github.repository_owner }}
        ADDONS_DATA: ${{ steps.info.outputs.addons }}
      run: |
        # Generate root README.md
        echo "Generating root README.md"
        gomplate --file=.README.tmpl --out=README.md

        # Generate individual add-on READMEs
        for addon in ${{ steps.info.outputs.readme }}; do
          echo "Generating README for ${addon}"
          # Use central template with ADDON_SLUG set to current addon directory
          export ADDON_SLUG="${addon}"
          gomplate --file=.README_ADDON.tmpl --out=${addon}/README.md
        done
