---
name: README Updates
description: "Update all or given READMEs"

inputs:
  addons:
    description: Addon-Name(s)
    required: false

runs:
  using: "composite"
  steps:
    - name: ℹ️ Gather Addon Info
      id: info
      shell: bash
      run: |
        data=()
        readme=()
        for directory in $(find ./ -maxdepth 2 -name config.json -o -name config.yaml -o -name config.yml | cut -d "/" -f2 | sort -u); do
          # Extract base image from Dockerfile (handle various patterns)
          base_image=""
          dockerfile="${directory}/Dockerfile"
          if [[ -f "$dockerfile" ]]; then
            # Look for BASE_IMAGE ARG or extract from first FROM statement with AS
            base_image=$(grep -E '^ARG BASE_IMAGE=' "$dockerfile" | sed 's/^ARG BASE_IMAGE=//' | tr -d '"')
            if [[ -z "$base_image" ]]; then
              # Extract from first FROM statement (e.g., "FROM image:tag AS name" or "FROM image:tag")
              base_image=$(grep -m1 '^FROM ' "$dockerfile" | sed -E 's/^FROM[[:space:]]+([^[:space:]]+).*/\1/')
            fi
          fi

          # Parse upstream version from base image (e.g., "v1.1.3" from "repo/image:v1.1.3")
          upstream_version=""
          upstream_image_repo=""
          upstream_badge_type=""
          if [[ -n "$base_image" ]]; then
            upstream_version=$(echo "$base_image" | grep -oE ':[^[:space:]]+' | tr -d ':')
            # Extract image repository without tag (e.g., "ghcr.io/user/repo" or "user/repo")
            upstream_image_repo=$(echo "$base_image" | sed 's/:[^[:space:]]*//')
            # Determine badge type based on registry
            if [[ "$upstream_image_repo" =~ ^ghcr\.io/ ]]; then
              upstream_badge_type="github"
              # Extract owner/repo from ghcr.io/owner/repo
              upstream_image_repo=$(echo "$upstream_image_repo" | sed 's|^ghcr\.io/||')
            else
              upstream_badge_type="docker"
            fi
          fi

          # Extract project_url from addon_info.json if it exists
          project_url=""
          info_file="${directory}/addon_info.json"
          if [[ -f "$info_file" ]]; then
            project_url=$(jq -r '.project_url // empty' "$info_file" 2>/dev/null || echo "")
          fi

          # Export variables so yq can read them via env()
          export base_image upstream_version project_url upstream_image_repo upstream_badge_type

          addon=$(yq e -N -M '. | {"name": .name, "slug": .slug, "version": .version, "description": .description, "arch": .arch, "base_image": env(base_image), "upstream_version": env(upstream_version), "project_url": env(project_url), "upstream_image_repo": env(upstream_image_repo), "upstream_badge_type": env(upstream_badge_type) }' -o=json -I=0 "${directory}/config.yaml")
          data+=("${addon}");
          readme+=("${directory}");
        done

        if [[ ! -z "${{ inputs.addons }}" ]]; then
          readme=("${{ inputs.addons }}")
        fi

        echo "readme=${readme[@]}" >> $GITHUB_OUTPUT;
        echo "Readme's to update: ${readme[@]}";

        addons=[$(IFS=, ; echo "${data[*]}")]
        echo "addons=${addons}" >> $GITHUB_OUTPUT;
        echo "Resolved addon data: ${addons}";
    - name: 📝 Generate README.md
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        REPOSITORY_URL: https://github.com/${{ github.repository }}
        ARCHITECTURES: "['aarch64', 'amd64', 'armhf', 'armv7']"
        ADDONS_DATA: ${{ steps.info.outputs.addons }}
      run: |
        curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.5/gomplate_linux-amd64
        chmod 755 /usr/local/bin/gomplate

        # Generate root README.md
        echo "Generating root README.md"
        gomplate --file=.README.tmpl --out=README.md

        # Generate individual add-on READMEs
        for addon in ${{ steps.info.outputs.readme }}; do
          echo "Generating README for ${addon}"
          # Use central template with ADDON_SLUG set to current addon directory
          export ADDON_SLUG="${addon}"
          gomplate --file=.README_ADDON.tmpl --out=${addon}/README.md
        done
